### ISSUE TITLE
Option to make copy to clipboard optional or not rely on xsel

### ISSUE THREAD

**Issue by Hsn723** [ekmartin/bibtex-search#1]
Using bibtex-search on Bash on Windows (WSL), I get an error related to xsel when selecting an article. I don't mind having to manually copy-paste the bibtex output, so being able to disable automatic clipboarding would be fine. Alternatively, some better clipboard support that doesn't rely on an X server running would be nice.

**Comment by ekmartin** [comment]
There used to be a `try-catch` around the clipboard stuff, as it doesn't really matter if it fails since we've already printed out the reference - not sure where it went. I've [added it back](https://github.com/ekmartin/bibtex-search/commit/c620d0eae167871738c5d193db676df15cec67af) in version 0.3.1 at least - feel free to test it out!

Optimally the prompt stuff should probably be outputted to stderr in the future, so `bibtex-search bayou >> sources.bib` would work, but I think there might be some issues with the color escape sequences.
